config/routes.rb
Adventures::Application.routes.draw do
  get "users/new"
  resources :locations
  resources :adventures
  resources :users
  get "pages/info"
  root :to =>redirect('/adventures')
  match '/signup',    to: 'users#new',          via: 'get'
  match '/help',      to: 'static_pages#help',  via: 'get'
  match '/info',      to: 'pages#info',         via: 'get'
  match '/locations', to: 'locations#index',    via: 'get'

end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	has_many :locations
end

app/models/location.rb
class Location < ActiveRecord::Base
	acts_as_mappable  #from geokit
	belongs_to :adventure
	validates :address, presence: true
	validates :adventure_id, presence: true
	geocoded_by :address
	after_validation :geocode
end

class LocationAwareController < ActionController::Base
	#this should help to avoid just giving the frontend server for the geocoded by ip address thing all the time
	#this is from geokit
	geocode_ip_address
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save {self.email = email.downcase} #standardize on saving lower case emails with a callback 
	validates :name, presence: true, length: {maximum: 25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX},uniqueness: {case_sensitive:false}
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_action :set_adventure, only: [:show, :edit, :update, :destroy]

  # GET /adventures
  # GET /adventures.json
  def index
    @adventures = Adventure.all
  end

  # GET /adventures/1
  # GET /adventures/1.json
  def show
  end

  # GET /adventures/new
  def new
    @adventure = Adventure.new
  end

  # GET /adventures/1/edit
  def edit
  end

  # POST /adventures
  # POST /adventures.json
  def create
    @adventure = Adventure.new(adventure_params)
    respond_to do |format|
      if @adventure.save
        format.html { redirect_to @adventure, notice: 'Adventure was successfully created.' }
        format.json { render action: 'show', status: :created, location: @adventure }
      else
        format.html { render action: 'new' }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adventures/1
  # PATCH/PUT /adventures/1.json
  def update
    respond_to do |format|
      if @adventure.update(adventure_params)
        format.html { redirect_to @adventure, notice: 'Adventure was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adventures/1
  # DELETE /adventures/1.json
  def destroy
    @adventure.destroy
    respond_to do |format|
      format.html { redirect_to adventures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adventure
      @adventure = Adventure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adventure_params
      params.require(:adventure).permit(:name, :country, :description, :picture, :budget, :link, :more_info, :completed, :submitted_by, :time)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    #create geokit location for session to display closest locations on map?
    #hmm maybe I want this to be a trait of the user instead of here in the index?
    respond_to do |format|
      format.html # index.hrml.erb
      format.xml { render xml: @locations}
      format.json { render json: @locations}
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @locations = Location.all
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :adventure_id, :latitude, :longitude)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/adventures/_form.html.erb
<%= form_for @adventure do |f| %>
  <% if @adventure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adventure.errors.count, "error") %> prohibited this adventure from being saved:</h2>

      <ul>
      <% @adventure.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
  <div class="field">
    <%= f.label :name, "Adventure Name" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.country_select :country %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
<!-- Removed due to bug in uploading pictures (Git 4)
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
-->
  <div class="field">
    <%= f.label :time, "How Long Will This Take in Days?" %><br>
    <%= f.number_field :time %>
  </div>
  <div class="field">
    <%= f.label :budget, "Expected Budget" %><br>
    <%= f.number_field :budget %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :more_info %><br>
    <%= f.text_field :more_info %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :submitted_by %><br>
    <%= f.text_field :submitted_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adventures/edit.html.erb
<% provide(:title, 'Edit') %>
<h1>Editing adventure</h1>

<%= render 'form' %>

<%= link_to 'Show', @adventure %> |
<%= link_to 'Back', adventures_path %>

app/views/adventures/index.html.erb
<% provide(:title, 'Home') %>
<h1>Lets Do Something!</h1>
<table class="table table-striped">
  <thead>
    <tr>
<!--    	<th>Picture</th> pictures are hard-->
    	<th>Name</th>
      	<th>Country</th>
      	<th>Description</th>
        <th>Budget</th> 
      	<th>Link</th>
 <!--     <th>More info</th>
      	<th>Completed</th> -->
      	<th>Submitted by</th>
      	<th></th>
      	<th></th>
      	<th></th>
    </tr>
  </thead>

  <tbody>
    <% @adventures.each do |adventure| %>
      <tr>
<!--      	<td><%= image_tag adventure.picture_url(:thumb) if adventure.picture? %></td> -->
      	<td><%= adventure.name %></td>
		    <td><%= adventure.country %></td>
        <td><%= adventure.description %></td>    
        <td><%= adventure.budget %></td> 
        <td><%= link_to adventure.link,adventure.link %></td>
<!--    <td><%= adventure.more_info %></td>
        <td><%= adventure.completed %></td> -->
        <td><%= adventure.submitted_by %></td>
        <td><%= link_to 'View', adventure, class: "btn btn-small" %></td>
        <td><%= link_to 'Add Location', new_location_path %></td>
        <td><%= link_to 'Edit', edit_adventure_path(adventure) %></td>
        <td><%= link_to 'Delete', adventure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adventure', new_adventure_path, class: "btn btn-large btn-primary" %> 

app/views/adventures/new.html.erb
<% provide(:title, 'New') %>
<h1>New adventure</h1>

<%= render 'form' %>

<%= link_to 'Back', adventures_path %>

app/views/adventures/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <%= image_tag(@adventure.picture_url, :width => 600, :align => "right") if @adventure.picture.present? %>
</p>

<p>
  <strong>Name:</strong>
  <%= @adventure.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @adventure.country %>
</p>

<p>
  <strong>Description:</strong>
  <%= @adventure.description %>
</p>

<p><strong>Duration:</strong>
  <%= @adventure.time %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @adventure.budget %>
</p>

<p>
  <strong>More info:</strong>
  <%= @adventure.more_info %>
</p>

<p>
  <strong>Link:</strong>
  <%= link_to @adventure.link, @adventure.link %>
</p>

<p>
  <strong>Submitted by:</strong>
  <%= @adventure.submitted_by %>
</p>

<p>
  <strong>Completed:</strong>
  <% if @adventure.completed? %>
    <%= check_box_tag('completed', @adventure.completed, false, :disabled => true) %>
  <% else %>
    Not Yet
  <% end %>
</p>

<%= link_to 'Add Location', new_location_path %> |
<%= link_to 'Edit Adventure', edit_adventure_path(@adventure) %> |
<%= link_to 'Back', adventures_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
	<a href="http://thesquirrelfish.com/">a squirrelfish app</a>
	by Heidi, all rights mine muah ha ha
	</small>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
 <%#two logos here okay? %>
  <%= link_to image_tag("BuffyTinyLogo.png", alt:"Buffy Logo"), 'http://thesquirrelfish.com', id:"logo" %>
  <%= link_to 'Do Something!', root_path, class: 'navbar-brand navbar-left', id:"logo" %>
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'New', new_adventure_path, class: 'navbar-right navbar-brand highlight-nav' %>
    <%= link_to 'Info', pages_info_path, class: 'navbar-right navbar-brand' %>
    <%= link_to 'Locations', locations_path, class: 'navbar-right navbar-brand' %>
    <%= link_to 'Users', users_path, class: 'navbar-right navbar-brand' %>
    <%= link_to 'Login', signup_path, class: 'navbar-right navbar-brand highlight-nav' %> 
  </div>
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Do Something |  <%=  content_for?(:title) ? yield(:title) : "Do Something" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Adventures" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "gmaps.js", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCP5NViYBg_el5x_7G8GaKgkxihZig_wvo">
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
       <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :adventure_id %><br>
    <%= f.number_field :adventure_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Showing locations near me</h1>
<div id="map-canvas" style='width:800px; height:400px;'>
  </div>
<!--this map actually shows up, but is generically stuck on Angkor Wat
I want this to show the adventure closest to the user, or perhaps the adventures within x miles of the user -->
<script type="text/javascript">
  function initialize() {
  var angkorWat = new google.maps.LatLng("13.4125", "103.8667");
    var mapOptions = {
      center: angkorWat,
      zoom: 4
    };
    var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
    var marker = new google.maps.Marker({
      position: angkorWat,
      map: map,
      title:"Angkor Wat placeholder!"
    });
  }

 google.maps.event.addDomListener(window, 'load', initialize);
</script> 

<div id="map-canvas" style='width:800px; height:400px;'></div>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Adventure</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.adventure_id %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
<!-- don't show all the places on a map, just the place thats closest to you on the above map 
  something like this might be nice for adding markers for more adventures in the future
      <script type="text/javascript">
        function setMarker() {
          var myLatLng = new google.maps.LatLng("<%= location.latitude %>", "<%= location.longitude %>");
          var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title:"Test"
          });
        google.maps.event.addDomListener(window,'load', setMarker);
      </script>
-->
    <% end %>
  </tbody>
</table>

<br>
<br>
<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Adventure:</strong>
  <%= @location.adventure_id %>
</p>

<div style='width:800px;'>
	<p>
		<strong>Map:</strong>
	</p>  

<script type="text/javascript">
    function initialize() {
		var myLatLng = new google.maps.LatLng( <%=@location.latitude%>,<%=@location.longitude%>);
        var mapOptions = {
        	center: myLatLng,
          	zoom: 12
    };
    var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

    var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: "myLatLngMarker"
        });
      }  
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

	<div id="map-canvas" style='width:800px; height:400px;'>
	</div>
	<p>
		<strong>Coords:</strong>
		Lat:<%= @location.latitude %>
		Long: <%= @location.longitude %>
	</p>
</div>
<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/pages/info.html.erb
<% provide(:title, 'Info') %>
<h1>So what is this?</h1>
<p>	this is an adventure planning app</p>
<p>	enter in some things you are interested in doing, and when you've got some free time pick from them later </p>
<p> this is also very much in development, so keep expectations low </p>

<h2>So who is doing this?</h2>
<p> Heidi - also known as TheSquirrelfish around the internet </p>
<p> check out my adventures in using this app on <a href="http://thesquirrelfish.com/blog">my blog</a></p>

<h3> You want to try it out?</h3>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>In development</h1>
<p>This app is still in development as of April 2015. Please hold off for a bit.</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
</br>
<p> Don't you want a personalized version?  By creating your own account you can choose from activities you've personally selected rather than those submitted by all users. </p>
<p> No information is sold to anybody, and we try not to get any info that's too private so we don't have to worry about protecting your privacy </p>